<a href="https://colab.research.google.com/github/CristianoDataScience/catboost_model/blob/main/REGRESS%C3%83O_COM_CATBOOST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## REGRESSÃO COM CATBOOST

In [2]:
#!pip3 install catboost

## Importando Bibliotecas

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from  sklearn.model_selection import train_test_split
from catboost import CatBoostRegressor

In [4]:
df = pd.read_csv('/content/drive/MyDrive/ml_project/housing.csv')
df.head(2)

RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0

In [6]:
independente = df.iloc[:, 0:3].values
independente

array([[ 6.575,  4.98 , 15.3  ],
       [ 6.421,  9.14 , 17.8  ],
       [ 7.185,  4.03 , 17.8  ],
       ...,
       [ 6.976,  5.64 , 21.   ],
       [ 6.794,  6.48 , 21.   ],
       [ 6.03 ,  7.88 , 21.   ]])

In [7]:
independente.shape

(489, 3)

In [13]:
dependente = df.iloc[:, 3].values

In [10]:
x_treino, x_teste, y_treino, y_teste = train_test_split(independente, dependente, test_size=0.3, random_state=0)

In [11]:
x_treino.shape, x_teste.shape

((342, 3), (147, 3))

In [22]:
catboost = CatBoostRegressor(iterations=100, learning_rate=0.08, depth=5, random_state=10)
catboost.fit(x_treino, y_treino)

0:	learn: 153885.2754929	total: 626us	remaining: 62ms
1:	learn: 145560.6000514	total: 1.71ms	remaining: 83.9ms
2:	learn: 138225.8372427	total: 2.47ms	remaining: 80ms
3:	learn: 131355.6293814	total: 3.26ms	remaining: 78.2ms
4:	learn: 125170.2577020	total: 4ms	remaining: 76.1ms
5:	learn: 119550.2226179	total: 4.7ms	remaining: 73.6ms
6:	learn: 114409.0672213	total: 5.41ms	remaining: 71.9ms
7:	learn: 109536.2116181	total: 6.28ms	remaining: 72.2ms
8:	learn: 105434.3594366	total: 7.02ms	remaining: 71ms
9:	learn: 101243.2460951	total: 7.75ms	remaining: 69.7ms
10:	learn: 97472.9802508	total: 8.48ms	remaining: 68.6ms
11:	learn: 93927.2207626	total: 9.18ms	remaining: 67.3ms
12:	learn: 90880.1445218	total: 9.87ms	remaining: 66.1ms
13:	learn: 87832.0734456	total: 10.6ms	remaining: 64.8ms
14:	learn: 85013.5932920	total: 11.3ms	remaining: 63.9ms
15:	learn: 82307.6915610	total: 12ms	remaining: 62.8ms
16:	learn: 79857.8824898	total: 12.7ms	remaining: 61.9ms
17:	learn: 77586.4911189	total: 13.4ms	remai

In [23]:
catboost.score(x_treino, y_treino)

0.8987749049972403

## Teste

In [24]:
catboost.score(x_teste, y_teste)

0.8356524921108562

In [25]:
previsao = catboost.predict(x_teste)

In [26]:
previsao

array([429400.01623192, 682595.02868122, 331243.97698003, 296222.91720886,
       494493.87846518, 263905.53234461, 332510.33447166, 415822.69648785,
       473356.34097678, 384911.86966413, 269459.57548172, 350494.04605895,
       475432.07209624, 236188.39757946, 460145.1882612 , 325011.53079013,
       459852.34147579, 533622.19993342, 419207.37214489, 624809.82783425,
       675771.08521338, 723808.08032618, 237389.73068411, 452499.57980866,
       396428.03776697, 922534.53446703, 762399.00820899, 927150.00498334,
       398075.0017192 , 431027.91269727, 281829.08536463, 397151.87260001,
       467664.15225401, 702032.35503146, 461395.29564721, 902800.92816049,
       484238.27027971, 261538.78665599, 482683.75197574, 528248.5184367 ,
       271685.94165107, 369422.52483921, 429194.50009351, 479687.66350916,
       326951.09175282, 374804.11446178, 489985.80383496, 314447.61478032,
       840083.29268409, 409737.02687785, 720294.76268985, 437172.90409723,
       567665.81226538, 3

In [27]:
# Fazendo previsões para valores distintos
valor_casa = catboost.predict([[8,12,25]])
valor_casa

array([484474.6242604])

## MÉTRICAS

In [28]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [29]:
# Erro médio Absoluto
mean_absolute_error(y_teste, previsao)

52043.380841851125

In [30]:
# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_teste, previsao))

69053.3516855943

## Validação Cruzada

In [31]:
from sklearn.model_selection import cross_val_score, KFold

In [32]:
# Separando os dados em folds
kfold = KFold(n_splits=12, shuffle=True, random_state=5)

In [35]:
# Criando o modelo
modelo = CatBoostRegressor(iterations=100, learning_rate=0.08, depth=5, random_state=10)
resultado = cross_val_score(modelo, x_treino, y_treino, cv=kfold)
resultado

0:	learn: 155011.9399540	total: 5.26ms	remaining: 520ms
1:	learn: 146777.9337848	total: 7.6ms	remaining: 372ms
2:	learn: 139028.0502972	total: 8.73ms	remaining: 282ms
3:	learn: 131999.2834869	total: 10.2ms	remaining: 244ms
4:	learn: 125588.9134815	total: 11.7ms	remaining: 223ms
5:	learn: 119714.3018770	total: 13.2ms	remaining: 207ms
6:	learn: 114566.1364229	total: 14.4ms	remaining: 192ms
7:	learn: 109609.8291848	total: 16.6ms	remaining: 191ms
8:	learn: 105075.0769889	total: 17.8ms	remaining: 180ms
9:	learn: 100891.2020236	total: 19.5ms	remaining: 175ms
10:	learn: 96980.3379337	total: 20.2ms	remaining: 164ms
11:	learn: 93450.0081237	total: 21.7ms	remaining: 159ms
12:	learn: 90240.4282090	total: 24.9ms	remaining: 167ms
13:	learn: 87357.1458873	total: 26.3ms	remaining: 162ms
14:	learn: 84707.2546128	total: 27.6ms	remaining: 157ms
15:	learn: 82092.6853894	total: 28.1ms	remaining: 148ms
16:	learn: 80053.1115594	total: 29.8ms	remaining: 145ms
17:	learn: 77793.7660341	total: 31.2ms	remaining:

array([0.80066813, 0.85215205, 0.75475349, 0.80568636, 0.83243773,
       0.86982657, 0.89960735, 0.78895393, 0.68202342, 0.92390916,
       0.84133315, 0.83851996])

In [36]:
# Usando a média e o desvio padrão
print("Coefiente de Determinação Médio: %.2f%%" % (resultado.mean()*100.0))

Coefiente de Determinação Médio: 82.42%
